### ISSUE TITLE
EntityManager always null problem

### ISSUE THREAD

**Issue by jpvasconcelos-m** [jpvasconcelos-m/easedesk#3]
when using test classes like TicketCreator.java or UserCreator.java im getting the following exception message 

> Exception in thread "main" java.lang.NullPointerException: Cannot invoke "javax.persistence.EntityManagerFactory.createEntityManager()" because "easedesk.infra.DAO.emf" is null
> 	at easedesk.infra.DAO.<init>(DAO.java:28)
> 	at easedesk.test.TicketCreator.main(TicketCreator.java:21)

**Comment by jpvasconcelos-m** [comment]
Removed Ticket and TicketCreator classes. These were someway causing this error even if only UserCreator was being executed.
